### ISSUE TITLE
About environment

### ISSUE THREAD

**Issue by 109318401ntut** [KAIST-HCIL/DeepFisheyeNet#1]
Hello, thank you for your amazing implementation.
Is this DeepFisheyeNet repo were developed on windows 10 ?

**Comment by KeunwooPark** [comment]
Hi.

It was developed on Ubuntu 18. But this repo can be run on any OS as long as it supports Pytorch, along with the packages in ```requrements.txt```

**Comment by 109318401ntut** [comment]
Thanks for your response.
